"""Creacion de tabla direcciones y relacion con usuarios

Revision ID: 4efe9e7bac51
Revises: 7e00664c5b34
Create Date: 2025-04-03 21:49:12.127555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efe9e7bac51'
down_revision = '7e00664c5b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calle', sa.Text(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('predeterminada', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direcciones')
    # ### end Alembic commands ###
