"""modificacion tabla productos

Revision ID: fff529244b7e
Revises: f08ea943a4b0
Create Date: 2025-04-10 19:17:18.561100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff529244b7e'
down_revision = 'f08ea943a4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_ordenes', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=False),
               # para cambiar tipos de dato usamos el parametro postgresql_using
               postgresql_using='fecha::timestamp without time zone',
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               postgresql_using='total::double precision',
               nullable=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
                postgresql_using='precio::double precision',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('detalle_ordenes', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
